task: our-nerf
gpus: [4,5]
exp_name: 'our-nerf_test_2'

####
src_views_num: 3
volume_pad: 0
depth_planes_num: 128
N_rays: 512
chunk_size: 2048
N_samples: 3
white_bkgd: False
render_scale: 0.5
input_ratio: 0.5
src_views_num: 4
net_width: [512]
fr_pos: 15
train_frames: 100
test_frames: 100
frame_id: 0
cascade_samples : [128]
samples_all : 148
start: 3353
bbox_sp : 10
dist : 250
weight_th : 0.05
semantic_weight : 0.01
lambda_depth : 0.1
lambda_fix : 1.
lambda_semantic_2d : 1.
lambda_3d : 1.
crf_seq: 5
max_depth : 100.
center_pose: [1360.034, 3845.649, 116.8115]
val_list : [3353, 3360, 3370, 3380, 3390, 3400, 3410, 3420, 3430]
depth_object : [9, 12, 35]
consistency_thres : 0.1
use_stereo : False
use_depth : True
detach : True
train_dataset_module: lib.dataloader.dataset
test_dataset_module: lib.dataloader.dataset

network_module: lib.network.network
loss_module: lib.train.loss

visualizer_module: lib.visualizer.visualizer

train_dataset:
    cam2world_root: '/data/datasets/KITTI-360/data_poses/2013_05_28_drive_0000_sync/cam0_to_world.txt'
    img_root: '/data/datasets/KITTI-360/2013_05_28_drive_0000_sync'
    bbx_root: '/data/datasets/KITTI-360/data_3d_bboxes'
    data_root: '/data/datasets/KITTI-360/'
    sequence: '2013_05_28_drive_0000_sync'
    split: 'train'

test_dataset:
    cam2world_root: '/data/datasets/KITTI-360/data_poses/2013_05_28_drive_0000_sync/cam0_to_world.txt'
    img_root: '/data/datasets/KITTI-360/2013_05_28_drive_0000_sync'
    bbx_root: '/data/datasets/KITTI-360/data_3d_bboxes'
    data_root: '/data/datasets/KITTI-360/'
    sequence: '2013_05_28_drive_0000_sync'
    split: 'val'

train:
    batch_size: 1
    lr: 5e-4
    weight_decay: 0.
    epoch: 50
    scheduler:
        type: 'exponential'
        gamma: 0.5
        decay_epochs: 80
    num_workers: 3

test:
    dataset: KITTI360Val
    batch_size: 1

ep_iter: 1000
save_ep: 1
eval_ep: 1
save_latest_ep: 1
log_interval: 1
