task: our-nerf
gpu: 5
exp_name: 'our-nerf_test_1'

####
N_rays: 1024
chunk_size: 2048
N_samples: 64
cascade_samples: 128
samples_all: 192
white_bkgd: False
fr_pos: 15
train_frames: 100
start: 3353
dist : 250
center_pose: [1360.034, 3845.649, 116.8115]
val_list : [3353, 3360, 3370, 3380, 3390, 3400, 3410, 3420, 3430]
use_stereo : False

train_dataset_module: lib.dataloader.dataset
test_dataset_module: lib.dataloader.dataset

network_module: lib.network.network
loss_module: lib.train.loss

visualizer_module: lib.visualizer.visualizer

train_dataset:
    cam2world_root: '/data/datasets/KITTI-360/data_poses/2013_05_28_drive_0000_sync/cam0_to_world.txt'
    img_root: '/data/datasets/KITTI-360/2013_05_28_drive_0000_sync'
    bbx_root: '/data/datasets/KITTI-360/data_3d_bboxes'
    data_root: '/data/datasets/KITTI-360/'
    sequence: '2013_05_28_drive_0000_sync'
    split: 'train'

test_dataset:
    cam2world_root: '/data/datasets/KITTI-360/data_poses/2013_05_28_drive_0000_sync/cam0_to_world.txt'
    img_root: '/data/datasets/KITTI-360/2013_05_28_drive_0000_sync'
    bbx_root: '/data/datasets/KITTI-360/data_3d_bboxes'
    data_root: '/data/datasets/KITTI-360/'
    sequence: '2013_05_28_drive_0000_sync'
    split: 'val'

train:
    batch_size: 1
    lr: 5e-4
    weight_decay: 0.
    epoch: 60
    scheduler:
        type: 'exponential'
        gamma: 0.5
        decay_epochs: 80
    num_workers: 3

test:
    dataset: KITTI360Val
    batch_size: 1

ep_iter: 1000
save_ep: 1
save_latest_ep: 1
log_interval: 1
